"""Generate a concise code index for AGENTS.md.

Parses every Python file under src/ using ast_tools and produces a
structured map of modules, classes, and public functions so agents can
locate code without broad searching.

Usage:
    python tools/generate_code_index.py                    # print to stdout
    python tools/generate_code_index.py --target agents-md # append to AGENTS.md
    python tools/generate_code_index.py --target standalone # write .code-index.md
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "tools"))

from ast_tools import ModuleInfo, parse_ast

# ── Configuration ────────────────────────────────────────────────────

SRC_DIRS: list[Path] = [PROJECT_ROOT / "src"]

EXCLUDE_DIRS: set[str] = {"__pycache__", "da2_genai_digital_donor_journey_backend.egg-info"}

EXCLUDE_FILES: set[str] = {"__init__.py"}

# Maximum symbols in the flat index table
MAX_SYMBOLS: int = 100

# Include _private functions in the index
INCLUDE_PRIVATE: bool = False

INDEX_HEADER = (
    "# Code Index\n\n"
    "> Auto-generated by `python tools/generate_code_index.py`. "
    "Do not edit manually.\n"
)

AGENTS_MD_MARKER = "# Code Index"


# ── Scanning ─────────────────────────────────────────────────────────


def _scan_modules(src_dirs: list[Path]) -> list[ModuleInfo]:
    """Parse all Python files under src_dirs."""
    modules: list[ModuleInfo] = []
    for src_dir in src_dirs:
        if not src_dir.exists():
            continue
        for py_file in sorted(src_dir.rglob("*.py")):
            if any(ex in py_file.parts for ex in EXCLUDE_DIRS):
                continue
            if py_file.name in EXCLUDE_FILES:
                continue
            try:
                info = parse_ast(str(py_file))
                modules.append(info)
            except (SyntaxError, FileNotFoundError):
                continue
    return modules


def _rel_path(abs_path: str) -> str:
    """Convert absolute path to project-relative with forward slashes."""
    try:
        return str(Path(abs_path).relative_to(PROJECT_ROOT)).replace("\\", "/")
    except ValueError:
        return abs_path


# ── Index Generation ─────────────────────────────────────────────────


def _build_module_map(modules: list[ModuleInfo]) -> list[dict[str, str]]:
    """Group modules by directory and summarize key symbols."""
    dir_map: dict[str, dict[str, list[str]]] = {}

    for mod in modules:
        rel = _rel_path(mod.path)
        parts = rel.split("/")
        # Use first two path components as the directory group
        if len(parts) >= 3:
            dir_key = "/".join(parts[:3])
        elif len(parts) >= 2:
            dir_key = "/".join(parts[:2])
        else:
            dir_key = parts[0]

        purpose = mod.docstring.strip().split("\n")[0] if mod.docstring else ""

        symbols: list[str] = []
        for cls in mod.classes:
            symbols.append(f"`{cls.name}`")
        for func in mod.functions:
            if not INCLUDE_PRIVATE and func.name.startswith("_"):
                continue
            symbols.append(f"`{func.name}()`")

        dir_map.setdefault(dir_key, {"purpose": "", "symbols": []})
        if purpose and not dir_map[dir_key]["purpose"]:
            dir_map[dir_key]["purpose"] = purpose
        dir_map[dir_key]["symbols"].extend(symbols)

    rows = []
    for dir_path, info in sorted(dir_map.items()):
        # Cap symbols per directory at 5
        syms = info["symbols"][:5]
        sym_str = ", ".join(syms)
        if len(info["symbols"]) > 5:
            sym_str += ", ..."
        rows.append(
            {"directory": dir_path, "purpose": info["purpose"], "symbols": sym_str}
        )
    return rows


def _build_symbol_index(modules: list[ModuleInfo]) -> list[dict[str, str]]:
    """Build a flat symbol index of top public classes and functions."""
    symbols: list[dict[str, str]] = []

    for mod in modules:
        rel = _rel_path(mod.path)
        for cls in mod.classes:
            if not INCLUDE_PRIVATE and cls.name.startswith("_"):
                continue
            symbols.append(
                {
                    "symbol": cls.name,
                    "file": rel,
                    "line": str(cls.lineno),
                    "type": "class",
                }
            )
        for func in mod.functions:
            if not INCLUDE_PRIVATE and func.name.startswith("_"):
                continue
            symbols.append(
                {
                    "symbol": func.name,
                    "file": rel,
                    "line": str(func.lineno),
                    "type": "async function" if func.is_async else "function",
                }
            )

    # Sort by file path then line number
    symbols.sort(key=lambda s: (s["file"], int(s["line"])))
    return symbols[:MAX_SYMBOLS]


def _detect_entry_points(modules: list[ModuleInfo]) -> list[str]:
    """Identify key entry points heuristically."""
    entries: list[str] = []
    keywords = {
        "main.py": "FastAPI app",
        "bedrock.py": "LLM client (Databricks/Bedrock)",
        "factory.py": "Pipeline factory",
        "aws_handler.py": "WebSocket Lambda handler",
        "insight_generator.py": "Smart Insight pipeline",
        "insight_cache.py": "Insight caching (L1+L2)",
        "sql_generator.py": "Text-to-SQL generator",
        "pipeline.py": "Conversational BI pipeline",
    }

    for mod in modules:
        rel = _rel_path(mod.path)
        filename = Path(mod.path).name
        if filename in keywords:
            # Find main class
            main_class = ""
            if mod.classes:
                main_class = f" → `{mod.classes[0].name}`"
            entries.append(f"- {keywords[filename]}: `{rel}`{main_class}")

    return entries


def generate_index() -> str:
    """Generate the full code index markdown."""
    modules = _scan_modules(SRC_DIRS)
    lines: list[str] = [INDEX_HEADER, ""]

    # Key entry points
    entries = _detect_entry_points(modules)
    if entries:
        lines.append("## Key Entry Points\n")
        lines.extend(entries)
        lines.append("")

    # Module map table
    module_map = _build_module_map(modules)
    if module_map:
        lines.append("## Module Map\n")
        lines.append("| Directory | Purpose | Key Symbols |")
        lines.append("|-----------|---------|-------------|")
        for row in module_map:
            lines.append(
                f"| `{row['directory']}` | {row['purpose'][:60]} | {row['symbols']} |"
            )
        lines.append("")

    # Symbol index
    symbol_index = _build_symbol_index(modules)
    if symbol_index:
        lines.append("## Symbol Index\n")
        lines.append("| Symbol | File | Line | Type |")
        lines.append("|--------|------|------|------|")
        for sym in symbol_index:
            lines.append(
                f"| `{sym['symbol']}` | `{sym['file']}` | {sym['line']} | {sym['type']} |"
            )
        lines.append("")

    return "\n".join(lines)


# ── Output Modes ─────────────────────────────────────────────────────


def _write_to_agents_md(index: str) -> None:
    """Append or replace the Code Index section in AGENTS.md."""
    agents_md = PROJECT_ROOT / "AGENTS.md"
    if not agents_md.exists():
        agents_md.write_text(index, encoding="utf-8")
        print(f"✓ Created {agents_md}")
        return

    content = agents_md.read_text(encoding="utf-8")

    if AGENTS_MD_MARKER in content:
        # Replace existing section (everything from marker to end of file
        # or next top-level heading)
        marker_pos = content.index(AGENTS_MD_MARKER)
        # Find next top-level heading after the marker
        rest = content[marker_pos + len(AGENTS_MD_MARKER) :]
        next_heading = -1
        for i, line in enumerate(rest.split("\n")):
            if i == 0:
                continue
            if line.startswith("# ") and not line.startswith("# Code Index"):
                next_heading = marker_pos + len(AGENTS_MD_MARKER) + sum(
                    len(l) + 1 for l in rest.split("\n")[:i]
                )
                break

        if next_heading > 0:
            content = content[:marker_pos] + index + "\n" + content[next_heading:]
        else:
            content = content[:marker_pos] + index
    else:
        content = content.rstrip() + "\n\n" + index

    agents_md.write_text(content, encoding="utf-8")
    print(f"✓ Updated {agents_md} with Code Index")


def _write_standalone(index: str) -> None:
    """Write index to .code-index.md."""
    out_path = PROJECT_ROOT / ".code-index.md"
    out_path.write_text(index, encoding="utf-8")
    print(f"✓ Written to {out_path}")


# ── CLI ──────────────────────────────────────────────────────────────


def main() -> None:
    """Entry point for the code index generator."""
    parser = argparse.ArgumentParser(
        description="Generate a code index for agent navigation"
    )
    parser.add_argument(
        "--target",
        choices=["agents-md", "standalone", "stdout"],
        default="stdout",
        help="Where to write the index (default: stdout)",
    )
    args = parser.parse_args()

    index = generate_index()

    if args.target == "agents-md":
        _write_to_agents_md(index)
    elif args.target == "standalone":
        _write_standalone(index)
    else:
        print(index)


if __name__ == "__main__":
    main()
